config/routes.rb
Rails.application.routes.draw do
  resources :classrooms
  root                'pages#home'
  #get  'index'     => 'classrooms#index'
  #get  'show'      => 'classrooms#show'
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  validates :classroom_name, presence: true, length: { minimum: 3, maximum: 50}
  validate  :picture_size

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "should be less than 5MB")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]

  # GET /classrooms
  # GET /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
    @classroom = Classroom.find(params[:id])
    @links = Classroom.all
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to @classroom, notice: 'Classroom was successfully created.' }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to @classroom, notice: 'Classroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: 'Classroom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:classroom_name, :classroom_total, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/classrooms/_form.html.erb
<%= simple_form_for(@classroom, html: {class: "form-signin", multipart: true}) do |f| %>
  <%= f.error_notification %>
    <%= f.input :classroom_name, required: true, label: false, placeholder: "Name", input_html: {class: "form-control"} %>
    <%= f.input :classroom_total, label: false, placeholder: "Starting point total", input_html: {class: "form-control"} %>
    <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    <%= f.button :submit %>
<% end %>

<script type="text/javascript">
  $('#classroom_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/classrooms/edit.html.erb
<h1>Editing Classroom</h1>

<div class="container">
  <%= link_to classrooms_path do %>
    <h4><i class="glyphicon glyphicon-chevron-left">Back</i></h4>
  <% end %>
</div>

<%= render 'form' %>

app/views/classrooms/index.html.erb
<h1 class="well">Classrooms <%= link_to '+', new_classroom_path %></h1>
<% @classrooms.each do |classroom| %>
  <div class="container">
    <h3><%= link_to classroom.classroom_name, classroom_path(classroom) %></h3>
    <p> points: <%= classroom.classroom_total %></p>
    <p>
      <%= link_to 'Edit', edit_classroom_path(classroom)%> /
      <%= link_to 'Delete', classroom, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
<% end %>
<br>

app/views/classrooms/new.html.erb
<h1 class="well">New Classroom</h1>

<div class="container">
  <%= link_to classrooms_path do %>
    <h4><i class="glyphicon glyphicon-chevron-left">Back</i></h4>
  <% end %>
</div>

<%= render 'form' %>

app/views/classrooms/show.html.erb
<div class="col-md-12 well">
  <div class="col-md-8">
    <h1 class="inline-block-left"><strong><%= @classroom.classroom_name %></strong></h1>
    <%= link_to edit_classroom_path do %>
      <p class="inline-block-right"><i class="glyphicon glyphicon-edit"></i></p>
    <% end %>
    <%= link_to classrooms_path do %>
      <p><i class="glyphicon glyphicon-chevron-left">Back</i></p>
    <% end %>
  </div>
  <div class="col-md-4">
    <h2>Points : <%= @classroom.classroom_total %></h2>
  </div>
  <div class="col-md-2 inline-block-right">
    <h1>
      <i class="glyphicon icons glyphicon-triangle-top"></i>
      <i class="glyphicon icons glyphicon-triangle-bottom"></i>
    </h1>
  </div>
</div>
<div class="col-md-12">
  <%= image_tag @classroom.picture.url if @classroom.picture? %>
</div>
<% @links.each do |classroom| %>
  <div class="container">
    <h4><%= link_to classroom.classroom_name, classroom_path(classroom) %> : <%= classroom.classroom_total %></h4>
  </div>
<% end %>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PointPad</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div class="container">
    <%= render 'layouts/messages' %>

    <%= yield %>

  </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1 class="well">Point-pad</h1>

<h2><%= link_to "sign up", "" %></h2>
<h2><%= link_to "log in", "" %></h>

<h2><%= link_to "classrooms", classrooms_path %></h2>
<h2><%= link_to "teachers", "" %></h2>